### ISSUE TITLE
Where is 'env' directory?

### ISSUE THREAD

**Issue by vvpgrp** [delagics/yii2-app-another#2]
D:\xampp\htdocs_my_projects\another.dev>php init
PHP Warning:  require(D:/xampp/htdocs/_my_projects/another.dev/app/env/index.php): failed to open stream: No such file or directory in D:\xampp\htdocs_my_projects\another.dev\init on line 24

**Comment by insane-dev** [comment]
Hi. I guess you are using dev-master, try 1.0.1 stable version. Last changes in master are not stable enough.

**Comment by vvpgrp** [comment]
I Installed by git clone: "git clone https://github.com/delagics/yii2-app-another.git another.dev"
Where can I download 1.0.1 stable version?

**Comment by insane-dev** [comment]
It is better to use composer for that:

```
composer create-project --prefer-dist delagics/yii2-app-another another.dev 1.0.1
```

Or with `git clone`:

```
git clone -b 1.0.1 git@github.com:delagics/yii2-app-another.git another.dev
```

Or just download needed version archive at [Releases page](https://github.com/delagics/yii2-app-another/releases)

**Comment by vvpgrp** [comment]
OK! Thanks! It worked!

**Comment by insane-dev** [comment]
Welcome.
