### ISSUE TITLE
Installed on cloud9

### ISSUE THREAD

**Issue by hdushku** [delagics/yii2-app-another#3]
Nice one!
I just installed it on cloud9 and the frontend is working perfectly.
But when I try to access /admin
It shows not found

**Comment by hdushku** [comment]
It's admin/
Thanks for this great startup app in YII2.

**Comment by insane-dev** [comment]
Welcome @hdushku, and thx for a good comment about this repo. 
As for this issue, maybe you'll have to improve your nginx or apache config.
