### ISSUE TITLE
Does it support postgresql?

### ISSUE THREAD

**Issue by pzzrudlf** [delagics/yii2-app-another#4]
hi, i wanna konw that it support postgresql. thanks.

**Comment by insane-dev** [comment]
Hi. App in general must support it, however I didn't test initialization process when using postgre sql. I'll test it, and write results in this issue.

**Comment by insane-dev** [comment]
Well I tried, and it worked.

All you have to do before initialization, is to properly set connection in .env file:

```
DB_HOST = localhost
DB_PORT = 5432
DB_NAME = another_db
DB_USERNAME = postgres
DB_PASSWORD = 
DB_CHARSET = utf8
DB_DSN = "pgsql:host=${DB_HOST};port=${DB_PORT};dbname=${DB_NAME}"
```

and remove 

``` php
$this->db->createCommand('SET foreign_key_checks = 0;')->execute();
// and
$this->db->createCommand('SET foreign_key_checks = 1;')->execute();
```

everywhere in `app/console/controllers/InitController`

**Comment by pzzrudlf** [comment]
i meet some errors such as this "
Yii Migration Tool (based on Yii v2.0.8)

Exception: SQLSTATE[HY000] [2006] MySQL server has gone away
(F:\pzzrudlf\another.pgsql\app\vendor\yiisoft\yii2\db\Connection.php: 547)

"
what's wrong ?

**Comment by pzzrudlf** [comment]
oh, i am using windows 10 x64

**Comment by insane-dev** [comment]
Did you change `mysql:` to `pgsql:` in your `.env` file in DB_DSN variable, like so

```
DB_DSN = "pgsql:host=${DB_HOST};port=${DB_PORT};dbname=${DB_NAME}"
```

`Exception: SQLSTATE[HY000] [2006] MySQL server has gone away` can tell that it is continuing connecting to MySQL instead of PostgreSQL.

**Comment by pzzrudlf** [comment]
i changed it. 
![image of my .env](http://i4.buimg.com/645464b70d25c662.png)

**Comment by pzzrudlf** [comment]
Is there some wrong about the configuration of postgresql?
below are my configuration of .env , pg_hba.cof and postgresql.conf
![my configuration](http://i4.buimg.com/b4a25ee1e11fdbe5.png)

**Comment by insane-dev** [comment]
You can specify settings explicitly in `app/base/config/main.php` in `db` component by removing env() function and replacing it with your static configuration.

Like so:

``` php
// file: app/base/config/main.php
//...
        'db' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'pgsql:host=localhost;port=5432;dbname=my_db',
            'username' => 'myusername',
            'password' => 'mypass',
            'charset' => 'utf8',
        ],
//...
```

That is just for you to ensure your settings is passed to yii application.
If it will not help, then you probably configured your PostgreSQL not properly or you passing wrong settings to yii configuration file.

Sorry but I've never used PostgreSQL in my projects.
