### ISSUE TITLE
Array to string conversion in LandSelect widget.

### ISSUE THREAD

**Issue by hdushku** [delagics/yii2-app-another#5]
I'am getting this error:
PHP Notice – yii\base\ErrorException
Array to string conversion
for front and admin in LangSelect.php widget

```
        }
        return strtr($this->template, [
            '{label}' => $this->encodeLabels ? Html::encode($this->label) : $this->label,
            '{url}' => $this->url,
            '{items}' => $this->items ? Dropdown::widget([
                'items' => $this->items,
                'encodeLabels' => $this->encodeLabels
            ]) : '',
        ]); // line 103 where the error shows
    }
}

/**
```

**Comment by insane-dev** [comment]
Hi, how do you call the widget in your view?

**Comment by hdushku** [comment]
I am using digitalocean.com to clone the app.
I followed the steps in github and imported the translated messeges in
front and back but when I try the index it shows the error.
Maybe it could be an php version problem because in cloud9 it is working
fine.
Thank you!

**Comment by insane-dev** [comment]
What PHP version you have on server where you are receiving error? 
I'll test it on the same version.

And please, past here a detailed error trace. Maybe in a format of image.

**Comment by hdushku** [comment]
The php version is:
PHP 5.5.9-1ubuntu4.17 (cli)
![arraytostring](https://cloud.githubusercontent.com/assets/8830905/16482243/2ced5358-3eaf-11e6-8456-9d56a824af0e.png)

**Comment by insane-dev** [comment]
Yeah there was a bug, thank you for help.

Try latest 1.0.4 release, or just update code in your LangSelect widget from 1.0.4 version.
