### ISSUE TITLE
PHP YII INIT

### ISSUE THREAD

**Issue by ghost** [delagics/yii2-app-another#6]
on php yii init:

Error: Class dektrium\rbac\Module does not exist

**Comment by insane-dev** [comment]
Ok, I think its becouse the name of rbac module class has changed: https://github.com/dektrium/yii2-rbac/blob/master/RbacWebModule.php

Thanks for issue, I'll make an update soon.

**Comment by insane-dev** [comment]
fixed by https://github.com/delagics/yii2-app-another/releases/tag/1.0.5
